export const popularDestinations = [
  'Paris, France',
  'London, UK',
  'Dubai, UAE',
  'New York, USA',
  'Tokyo, Japan',
  'Bali, Indonesia',
  'Rome, Italy',
  'Istanbul, Turkey',
  'Barcelona, Spain',
  'Bangkok, Thailand',
  'Amsterdam, Netherlands',
  'Singapore',
  'Maldives',
  'Seoul, South Korea',
  'Sydney, Australia',
  'Santorini, Greece',
  'Prague, Czech Republic',
  'Lisbon, Portugal',
  'Vienna, Austria',
  'Berlin, Germany',
  'Cape Town, South Africa',
  'Cairo, Egypt',
  'Rio de Janeiro, Brazil',
  'Mexico City, Mexico',
  'Toronto, Canada',
  'Hong Kong',
  'Marrakech, Morocco',
  'Kyoto, Japan',
  'Florence, Italy',
  'Venice, Italy',
  'Phuket, Thailand',
  'Hanoi, Vietnam',
  'Buenos Aires, Argentina',
  'Zurich, Switzerland',
  'Munich, Germany',
  'San Francisco, USA',
  'Los Angeles, USA',
  'Las Vegas, USA',
  'Madrid, Spain',
  'Dublin, Ireland',
  'Kuala Lumpur, Malaysia',
  'Mumbai, India',
  'Delhi, India',
  "Cox's Bazar, Bangladesh",
  'Sylhet, Bangladesh',
  'Athens, Greece',
  'Moscow, Russia',
  'Stockholm, Sweden',
  'Oslo, Norway',
  'Brussels, Belgium',
]